export const rulerInfo = [
  { num: 0, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 1, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 2, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 3, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 4, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 5, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 6, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 7, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 8, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 9, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 10, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 11, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 12, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 13, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 14, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 15, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 16, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 17, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 18, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 19, serif: "|", id: Math.random().toString(16).slice(2) },
  { num: 20, serif: "|", id: Math.random().toString(16).slice(2) },
];
